### ISSUE TITLE
Make a Login/ Sign up form 

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/FoodSaver20008#11]
The user should be able to enter his email, password and while logging in user should have the option of logging in through OTP.

**Comment by mohit200008** [comment]
Only thr frontend has to be made for this

**Comment by kanishak11-cyber** [comment]
hello sir i want to work on this

**Comment by mohit200008** [comment]
Yes @kanishak11-cyber  go ahead

**Comment by mohit200008** [comment]
After creating the login signup also when someone clicks on login he/she should be redirected to the homepage.
And login page should have a new here? Sign up and forget password link

**Comment by kanishak11-cyber** [comment]
sir will u provide database or i have to made it

**Comment by mohit200008** [comment]
I will create a seperate issue for that

**Comment by kanishak11-cyber** [comment]
![image](https://user-images.githubusercontent.com/84625838/147492828-b17dd2fa-428c-43c2-b6b5-3061976e01b0.png)
![image](https://user-images.githubusercontent.com/84625838/147492835-157fe007-b682-4eab-b264-6521ed21a63f.png)

Is it okay now?

**Comment by mohit200008** [comment]
can you add a section for login through top @kanishak11-cyber

**Comment by kanishak11-cyber** [comment]
> can you add a section for login through top @kanishak11-cyber 

Yeah sure
