### ISSUE TITLE
convert the Class component into functional component

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/FoodSaver20008#2]
the class component needs to converted to functional components where ever class component is used.

**Comment by copyNinja1219** [comment]
working on it.

**Comment by mohit200008** [comment]
Is the website working without any errors ???

**Comment by copyNinja1219** [comment]
Yesss

**Comment by copyNinja1219** [comment]
@mohit200008 #15 done .

**Comment by copyNinja1219** [comment]
@mohit200008  #34 done
