### ISSUE TITLE
Create the login signup for the application

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/FoodSaver20008#22]
https://www.figma.com/file/DKdAeAkhaApFGUfDmj0GBX/FoodSaver-Login%2Fsignup?node-id=0%3A1
Only frontend has to be made for this.

**Comment by RishiKumarRay** [comment]
Do we have to make login signup page as present in this link

**Comment by mohit200008** [comment]
yes

**Comment by RishiKumarRay** [comment]
I am not getting the yellow part in sign and sign up page, can you please elaborate and can you please provide the background images that is in the sign in page?

**Comment by mohit200008** [comment]
you can other colour combination too

**Comment by mohit200008** [comment]
It should look appealing and go with the overall design and it should the inputs and links mentioned in the design

**Comment by Shlok1999** [comment]
If this issue is availiable, please assign this issue to me

**Comment by mohit200008** [comment]
The issue is resolved @Shlok1999
