### ISSUE TITLE
Add a "how to contribute" section in the readme 

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/FoodSaver20008#3]
Make sure it includes all the steps and also add some links for GitHub learning resources. Add this section at the bottom

**Comment by rushikeshadhav** [comment]
Ok I will add all steps for contributing

**Comment by mohit200008** [comment]
yeah sure @rushikeshadhav  go ahead

**Comment by mohit200008** [comment]
Are you contributing under SWOC 2.0??

**Comment by rushikeshadhav** [comment]
Yes I am contributing under SWOC 2.0
