### ISSUE TITLE
Fix the styles on Recipe Page, Title is overlapping

### ISSUE THREAD

**Issue by shaunpurslow** [mohit200008/FoodSaver20008#35]
<img width="1802" alt="Screen Shot 2022-01-08 at 2 31 12 PM" src="https://user-images.githubusercontent.com/64987681/148660683-d9c69e2e-6920-446d-af11-06ef4467941a.png">

-Make font smaller for the title or make box containers wider

**Comment by mohit200008** [comment]
You can work on this @shaund16  after you finish #30

**Comment by ankushj0801** [comment]
I would like to work on this.

**Comment by SattyamSamania** [comment]
hey @mohit200008 Can I work on this issue?
