### ISSUE TITLE
Fix styles when clicking Ingredients button on Recipe Page

### ISSUE THREAD

**Issue by shaunpurslow** [mohit200008/FoodSaver20008#37]
When clicking ingredients, pushes the row of recipes to the bottom of the page. The ingredients description is bunched up 
maybe making it wider so it is easily readable.

**Comment by mohit200008** [comment]
go ahead @shaund16  you can work on this

**Comment by shaund16** [comment]
@mohit200008 yes I am, however it’s taken me a little longer than expected. I am sick right now. When I get better I’ll work on it

**Comment by aktamoli0910** [comment]
Heyy @shaund16, hope you are doing well. Any update on the issue?

**Comment by shaund16** [comment]
@aktamoli0910 Thanks for checking in, unfortunately, things got busy over here on my end and I won't be able to tackle this. You may want to unassign me and have someone else tackle this issue. Thanks

**Comment by Dibyendu303** [comment]
Can I work on this issue ?

**Comment by mohit200008** [comment]
yes go ahead @Dibyendu303

**Comment by Dibyendu303** [comment]
Hey, I have submitted a PR #55 . Can you please check and revert me back.
