### ISSUE TITLE
Create a cancel button on add food page

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/FoodSaver20008#41]
When a user clicks on the cancel button the form should disappear.

**Comment by bhavyastar** [comment]
I would like to work on this issue.

**Comment by bhavyastar** [comment]
Will you assign this to me?

**Comment by mohit200008** [comment]
yes go ahead @bhavyastar

**Comment by bhavyastar** [comment]
Okay

**Comment by bhavyastar** [comment]
Then, Assign this to me

**Comment by shrinishant** [comment]
@mohit200008 can I please work on this issue?

**Comment by aktamoli0910** [comment]
Any update @bhavyastar ??

**Comment by unnati-dot** [comment]
@mohit200008 I would like to work on this issue. Can you please assign this to me?

**Comment by mohit200008** [comment]
Yes @unnati-dot  go ahead
