### ISSUE TITLE
Make hindi page similar to Home page 

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/FoodSaver20008#42]
Recreate the Hindi page, and make it the same as the Home page. Use the images folder in the src for the pictures.

**Comment by Kanika637** [comment]
Only the content language has to be changed and the rest of the page remains the same...is it? @mohit200008

**Comment by Kanika637** [comment]
I would like to work on this issue...

**Comment by mohit200008** [comment]
Go ahead @Kanika637

**Comment by mohit200008** [comment]
> Only the content language has to be changed and the rest of the page remains the same...is it? @mohit200008

the hindi page should be like the english page including the language and the layout and design

**Comment by Kanika637** [comment]
Made the PR, there is only one flaw the previous navbar is still there along with the Hindi one as it is the default in all the pages

**Comment by ankushj0801** [comment]
I would like to work on this. Please assign it to me.

**Comment by mohit200008** [comment]
yes @ankushj0801  go ahead

**Comment by ankushj0801** [comment]
how to connect with you? @mohit200008

**Comment by ankushj0801** [comment]
The site is  not opening. please help @mohit200008

**Comment by mohit200008** [comment]
What's the error ?

**Comment by ankushj0801** [comment]
Its working now. there was some error with the npm install.

**Comment by ankushj0801** [comment]
I have made PR for this issue. please check it.
