### ISSUE TITLE
Make Proper Routes for the App, Prevent Unnecessary reloads while navigating & Support Background Functionalities

### ISSUE THREAD

**Issue by shrinishant** [mohit200008/FoodSaver20008#46]
Right Now, the routes of the app are not developed well. And this anomaly is prohibiting the app to work well with unnecessary reloads of the components/pages while navigating through the app. This is not letting the app to leverage the power of React itself. And these reloads are causing the background functionalities not to keep track of food adds & the  functions defined.

**Comment by mohit200008** [comment]
You can work on this @shrinishant  go ahead
