### ISSUE TITLE
Create a after 7 days section on the home page

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/FoodSaver20008#7]
The sections After 7 days , and other sections should be in the form of cards .

**Comment by mohit200008** [comment]
yes

**Comment by mohit200008** [comment]
also style the cards

**Comment by arpita221b** [comment]
Ok sure

**Comment by mohit200008** [comment]
can you send a sc of the final layout ????

**Comment by arpita221b** [comment]
Hey, I did attach a screenshot in the PR.

**Comment by mohit200008** [comment]
Its good add the after 7 days section too

**Comment by mohit200008** [comment]
Just change the in 7 days section to after 7 days and we're good to go

**Comment by arpita221b** [comment]
It's done!
