### ISSUE TITLE
Redesign the form

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/FoodSaver20008#9]
Redesign the form on the add food page and The Newfoodform component should be in functional component making use of hooks.

**Comment by arpita221b** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by mohit200008** [comment]
sure @arpita221b  go ahead

**Comment by arpita221b** [comment]
Hey!
For now, this is what the form looks like.
![Screenshot (1211)](https://user-images.githubusercontent.com/56889637/145991107-0f026f6e-49af-437f-8cdd-2b9342038614.png)

Do tell me if any other changes are needed. 
Also if it looks fine I'll create a pull request and we can modify it later.

**Comment by mohit200008** [comment]
The border radius can be increased for the input bars and submit button rest is good work @arpita221b

**Comment by arpita221b** [comment]
Okay, I'll work on that.
Thanks!!!!
